# fly.toml app configuration file generated for grok-bot on 2026-01-12T00:41:51-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grok-bot'
primary_region = 'ord'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_PATH = '/data/grok.db'

[[mounts]]
  source = 'grok_data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
