name: Deploy to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-discord:
    name: Deploy Discord Bot
    runs-on: ubuntu-latest
    concurrency: deploy-discord
    steps:
      - uses: actions/checkout@v4

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Discord Bot
        run: flyctl deploy --config fly.discord.toml --ha=false

  deploy-telegram:
    name: Deploy Telegram Bot
    runs-on: ubuntu-latest
    concurrency: deploy-telegram
    steps:
      - uses: actions/checkout@v4

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Telegram Bot
        run: flyctl deploy --config fly.telegram.toml --ha=false
